const beats = [
  { location: "BACKSTAGE / 10 MINUTES TO CURTAIN", type: "COMEDY", line: "The lead actor whispers: “I forgot every line… except the final one.”", choices: [["Make the final line the opening.", 18, "Bold reversal. The room leans in."], ["Hand them a cue card and hope.", 5, "It works, but the scene starts flat."], ["Cancel the show and rehearse.", -12, "Safe, but the momentum leaves the building."]] },
  { location: "DINER BOOTH / 2:13 A.M.", type: "MYSTERY", line: "Your friend puts a tiny key on the table. “It only opens if you’re honest.”", choices: [["Ask what the key unlocks.", 4, "A fair question—but not a revealing one."], ["Tell them the secret you were avoiding.", 18, "Truth raises the stakes. Nice instinct."], ["Slide the key back without looking.", -9, "The tension goes quiet instead of sharp."]] },
  { location: "ELEVATOR / BETWEEN FLOORS", type: "ROMANCE", line: "The lights cut out. Your ex laughs in the dark: “Of course this would happen to us.”", choices: [["Laugh, then admit you missed that laugh.", 18, "Specific and vulnerable. The room softens."], ["Call building maintenance immediately.", 2, "Practical, if a little unromantic."], ["Pretend you never heard them.", -11, "The silence becomes a wall."]] },
  { location: "PARKING LOT / AFTER THE CONCERT", type: "HEIST", line: "The getaway car will not start. The security guard is humming the song you stole.", choices: [["Offer the guard backstage passes to next year’s show.", 14, "A strange bargain creates a fun turn."], ["Pop the hood and start guessing.", -6, "The clock keeps winning."], ["Start humming the harmony.", 19, "Perfect. You found the unexpected connection."]] },
  { location: "ROOFTOP / SUNRISE", type: "DRAMA", line: "Your co-founder hands you the last train ticket and says: “One of us gets to leave.”", choices: [["Tear the ticket in half and invent a third choice.", 9, "Defiant—but the problem still needs a plan."], ["Give them the ticket and name what it costs you.", 19, "Clear sacrifice gives the ending weight."], ["Take it without saying goodbye.", -13, "A strong image, but no emotional payoff."]] }
];

const ui = Object.fromEntries(["start-button","game-panel","scene-location","scene-type","scene-line","choices","feedback","round-label","streak-label","energy-value","energy-fill","score-value","score-fill","result-dialog","result-title","result-copy","final-score","play-again","close-dialog","intro-copy"].map(id => [id, document.getElementById(id)]));
let round = 0, score = 0, energy = 50, streak = 0;
const pad = n => String(Math.max(0, n)).padStart(3, "0");

function updateHud() { ui.roundLabel.textContent = `REHEARSAL ${String(Math.min(round + 1, beats.length)).padStart(2, "0")} / 05`; ui.streakLabel.textContent = `ON A ROLL ×${streak}`; ui.energyValue.textContent = energy; ui.energyFill.style.width = `${energy}%`; ui.scoreValue.textContent = pad(score); ui.scoreFill.style.width = `${Math.min(100, score)}%`; }
function renderRound() { const beat = beats[round]; ui.sceneLocation.textContent = beat.location; ui.sceneType.textContent = beat.type; ui.sceneLine.textContent = `“${beat.line}”`; ui.feedback.textContent = ""; ui.choices.replaceChildren(...beat.choices.map(([text, points, feedback], i) => { const button = document.createElement("button"); button.type = "button"; button.className = "choice"; button.textContent = `${String.fromCharCode(65 + i)} — ${text}`; button.addEventListener("click", () => choose(button, points, feedback)); return button; })); updateHud(); }
function choose(button, points, feedback) { const buttons = [...ui.choices.querySelectorAll("button")]; buttons.forEach(item => item.disabled = true); button.classList.add("is-picked"); score += Math.max(0, points); energy = Math.max(0, Math.min(100, energy + points)); streak = points >= 14 ? streak + 1 : 0; ui.feedback.textContent = feedback; updateHud(); window.setTimeout(() => { round += 1; round < beats.length ? renderRound() : finish(); }, 1000); }
function finish() { ui.finalScore.textContent = pad(score); const excellent = score >= 70; ui.resultTitle.textContent = excellent ? "You made it sing." : "You kept it moving."; ui.resultCopy.textContent = excellent ? "Every choice gave the scene a sharper turn. The audience is still talking." : "You found a path through the chaos. Run it again and chase a bigger applause."; ui.resultDialog.showModal(); }
function start() { round = 0; score = 0; energy = 50; streak = 0; ui.startButton.classList.add("is-hidden"); ui.introCopy.classList.add("is-hidden"); ui.gamePanel.classList.remove("is-hidden"); renderRound(); }
ui.startButton.addEventListener("click", start); ui.playAgain.addEventListener("click", () => { ui.resultDialog.close(); start(); }); ui.closeDialog.addEventListener("click", () => ui.resultDialog.close());
